create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  service text,
  deadline text,
  notes text,
  venmo_handle text,
  source_link text,
  selected_colors text[],
  allow_gallery_post boolean default false,
  file_names text[],
  file_paths text[],
  status text default 'new',
  created_at timestamptz default now()
);

alter table public.orders enable row level security;

create policy "Allow anon inserts" on public.orders
for insert to anon
with check (true);

create policy "Allow anon reads" on public.orders
for select to anon
using (true);

insert into storage.buckets (id, name, public)
values ('print-uploads', 'print-uploads', false)
on conflict (id) do nothing;

create policy "Allow anon uploads" on storage.objects
for insert to anon
with check (bucket_id = 'print-uploads');

create policy "Allow anon reads of uploads" on storage.objects
for select to anon
using (bucket_id = 'print-uploads');
